[package]
name = "lox"
version = "0.1.0"
edition = "2024"
authors = ["Laith Altarabishi <laithaustin@utexas.edu>"]
description = "A Rust implementation of the Lox programming language"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"

[dev-dependencies]
criterion = "0.5"
test-case = "3.3"
